webtalk_init -webtalk_dir C:/Users/sebas/Desktop/newZDUPproject/uBBezPar/sumator/sumator.sim/sim_1/behav/xsim/xsim.dir/sumator_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jun 13 11:54:31 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0224cfba-932a-40a7-8283-c3f791126dcd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1e5ba97fb8f9416e9d42eb6c920a7dd1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "25" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3600X 6-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3793 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "51 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "6" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.92_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16476_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4220848992 -regid "" -xml C:/Users/sebas/Desktop/newZDUPproject/uBBezPar/sumator/sumator.sim/sim_1/behav/xsim/xsim.dir/sumator_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/sebas/Desktop/newZDUPproject/uBBezPar/sumator/sumator.sim/sim_1/behav/xsim/xsim.dir/sumator_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/sebas/Desktop/newZDUPproject/uBBezPar/sumator/sumator.sim/sim_1/behav/xsim/xsim.dir/sumator_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
