# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sumator_design/sumator_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sumator_design || ORIG_REF_NAME==sumator_design} -quiet] -quiet

# IP: bd/sumator_design/ip/sumator_design_microblaze_0_0/sumator_design_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sumator_design_microblaze_0_0 || ORIG_REF_NAME==sumator_design_microblaze_0_0} -quiet] -quiet

# IP: bd/sumator_design/ip/sumator_design_sum_ip_0_0/sumator_design_sum_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sumator_design_sum_ip_0_0 || ORIG_REF_NAME==sumator_design_sum_ip_0_0} -quiet] -quiet

# IP: bd/sumator_design/ip/sumator_design_dlmb_v10_0/sumator_design_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sumator_design_dlmb_v10_0 || ORIG_REF_NAME==sumator_design_dlmb_v10_0} -quiet] -quiet

# IP: bd/sumator_design/ip/sumator_design_ilmb_v10_0/sumator_design_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sumator_design_ilmb_v10_0 || ORIG_REF_NAME==sumator_design_ilmb_v10_0} -quiet] -quiet

# IP: bd/sumator_design/ip/sumator_design_dlmb_bram_if_cntlr_0/sumator_design_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sumator_design_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==sumator_design_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/sumator_design/ip/sumator_design_ilmb_bram_if_cntlr_0/sumator_design_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sumator_design_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==sumator_design_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/sumator_design/ip/sumator_design_lmb_bram_0/sumator_design_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sumator_design_lmb_bram_0 || ORIG_REF_NAME==sumator_design_lmb_bram_0} -quiet] -quiet

# IP: bd/sumator_design/ip/sumator_design_mdm_1_0/sumator_design_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sumator_design_mdm_1_0 || ORIG_REF_NAME==sumator_design_mdm_1_0} -quiet] -quiet

# IP: bd/sumator_design/ip/sumator_design_clk_wiz_1_0/sumator_design_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sumator_design_clk_wiz_1_0 || ORIG_REF_NAME==sumator_design_clk_wiz_1_0} -quiet] -quiet

# IP: bd/sumator_design/ip/sumator_design_rst_clk_wiz_1_100M_0/sumator_design_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sumator_design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==sumator_design_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/sumator_design/ip/sumator_design_microblaze_0_axi_periph_0/sumator_design_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sumator_design_microblaze_0_axi_periph_0 || ORIG_REF_NAME==sumator_design_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: bd/sumator_design/sumator_design_ooc.xdc
