# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sum_design/sum_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_design || ORIG_REF_NAME==sum_design} -quiet] -quiet

# IP: bd/sum_design/ip/sum_design_processing_system7_0_0/sum_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_design_processing_system7_0_0 || ORIG_REF_NAME==sum_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/sum_design/ip/sum_design_sum_ip_0_0/sum_design_sum_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_design_sum_ip_0_0 || ORIG_REF_NAME==sum_design_sum_ip_0_0} -quiet] -quiet

# IP: bd/sum_design/ip/sum_design_ps7_0_axi_periph_0/sum_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==sum_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/sum_design/ip/sum_design_rst_ps7_0_50M_0/sum_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==sum_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/sum_design/ip/sum_design_auto_pc_0/sum_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_design_auto_pc_0 || ORIG_REF_NAME==sum_design_auto_pc_0} -quiet] -quiet

# XDC: bd/sum_design/sum_design_ooc.xdc
