# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/sebas/Desktop/newZDUPproject/zynqBezPar/sumator/sumator.srcs/sources_1/bd/sum_design/ip/sum_design_processing_system7_0_0/sum_design_processing_system7_0_0.xci
# IP: The module: 'sum_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sebas/Desktop/newZDUPproject/zynqBezPar/sumator/sumator.srcs/sources_1/bd/sum_design/ip/sum_design_processing_system7_0_0/sum_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sum_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/sebas/Desktop/newZDUPproject/zynqBezPar/sumator/sumator.srcs/sources_1/bd/sum_design/ip/sum_design_processing_system7_0_0/sum_design_processing_system7_0_0.xci
# IP: The module: 'sum_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sebas/Desktop/newZDUPproject/zynqBezPar/sumator/sumator.srcs/sources_1/bd/sum_design/ip/sum_design_processing_system7_0_0/sum_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sum_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
